### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by pokowaka** [rozzzly/vscode-prompt-debug#15]
Is it possible to add a LICENSE? That way I know if I can reuse some of your code or not.

**Comment by rozzzly** [comment]
@pokowaka, thanks for your inquiry.

The `package.json` has always had the `license` field set to `MIT` but I've just updated (see #16) to include an explicit `LICENSE.md`

Not sure why you'd want to reuse any of this though. I haven't really touched it in over a year, not even sure if it works right now TBH. 🤷‍♂
