### ISSUE TITLE
Please update doc to use new command variable syntax

### ISSUE THREAD

**Issue by weinand** [rozzzly/vscode-prompt-debug#3]
Some months ago we've changed the command variable syntax to use a ':' separator because the '.' was ambiguous and difficult to read. After deprecating the old syntax for some milestones we've then removed support for it. 

This makes your very useful extension difficult to use because the documentation still uses the old syntax.

It would be great if you could change
     `${command.prompt-debug.resolve}`
to
     `${command:prompt-debug.resolve}`.

Thanks a lot.

/cc @Brocco

**Comment by rozzzly** [comment]
Just merged #2.

**Comment by weinand** [comment]
@rozzzly Could you please publish your extension again so that the README on the Marketplace shows the fixed content?
Thanks!
